// Generated by IcedCoffeeScript 1.8.0-d
(function() {
  var Base;

  exports.Base = Base = (function() {
    function Base(_arg) {
      this.publicKey = _arg.publicKey, this.secretKey = _arg.secretKey, this.lib = _arg.lib;
    }

    Base.prototype.genFromSeed = function(_arg) {
      var seed, tmp;
      seed = _arg.seed;
      tmp = this.lib.js.sign.keyPair.fromSeed(b2u(seed));
      this.secretKey = u2b(tmp.secretKey);
      this.publicKey = u2b(tmp.publicKey);
      return {
        secretKey: this.secretKey,
        publicKey: this.publicKey
      };
    };

    return Base;

  })();

}).call(this);
